### ISSUE TITLE
Localization /  Message Customization

### ISSUE THREAD

**Issue by jcdesimp** [jcdesimp/Landlord#13]
Rather than using hardcoded strings for messages and words that are shown to players, the messages should be configurable externally via something such as a "message.yml" file.
- Configurable option of which file to use.
- "english.yml" would be the default/template.
- Possibly add something like "pirate.yml" or "piglatin.yml" to use as an example of alternate language configurations.

**Comment by jamierocks** [comment]
Just use Java's default Properties class

**Comment by jcdesimp** [comment]
@jamierocks I was just gonna extend Bukkit's YamlConfiguration class. I need to sort out all the hardcoded strings that are already there first, which I've already started to do.

**Comment by jamierocks** [comment]
YML just doesn't seem like the right thing to use for this.

**Comment by jcdesimp** [comment]
@jamierocks I want it to be easily configurable by the server owners as well.

**Comment by jamierocks** [comment]
Properties files are easily configurable?
<code>
player.quit=%1 has quit the game.
</code>

**Comment by jcdesimp** [comment]
@jamierocks I plan on having the messages sorted in a hierarchical way. Command output, help info... should be logical. There will be a default bundled inside the plugin which will get referenced if the value is not found in the user configurable one. 

What advantages do Java properties offer for this? If you can convince me I'll consider it :)

**Comment by jamierocks** [comment]
Java's properties are just <code>key=value</code> and comments are like <code># this is a comment</code> So to do it in a hierarchical way you would do:
<code>
# player events
player.join=%1 has joined the game!
player.quit=%1 has quit the game!

# server events
server.shutdown=The server is shutting down!
</code>

**Comment by jcdesimp** [comment]
I don't really see how that would make it easier, only more annoying, With yaml I only need to write out a parent node once.

- player:
   - join: "#{player} joined!"
   - quit: "#{player} quit!"
