### ISSUE TITLE
Claim Land Issue

### ISSUE THREAD

**Issue by MrFrostmaul** [jcdesimp/Landlord#21]
Got an issue when trying to run  /land claim.
The plugin is started correctly and no errors until this command. It has the Internal error occurred ingame and this is the console log: http://pastebin.com/ZG0TVH18

Running latest version of plugin (1.3) and latest version of Spigot 1.8
Any help with this one?

**Comment by jcdesimp** [comment]
@MrFrostmaul I think I know what your problem is. Upgrade to the latest worldguard with spigot 1.8 support and let me know if that fixes it.

**Comment by MrFrostmaul** [comment]
Sorry for being an idiot lol. Thanks :)

**Comment by jcdesimp** [comment]
@MrFrostmaul No problem, took me a while to figure that out while I was updating for 1.8 xD
