### ISSUE TITLE
Add unlimited user defined "extra" amounts of claims

### ISSUE THREAD

**Issue by jcdesimp** [jcdesimp/Landlord#25]
Allow for a variable amount of "landlord.limit.extra" config as opposed to just five.

**Comment by DiscoveriesMC** [comment]
Cannot wait for this, it will allow me to give players more claims than the base amounts.

**Comment by Battelman2** [comment]
Perhaps a feature of Landlord API (version 2.0). Definitely slated for inclusion.

**Comment by Battelman2** [comment]
This is a smaller part of a larger issue. I'm closing this issue. Reference #39
