### ISSUE TITLE
Creeper Explosions not blocked?

### ISSUE THREAD

**Issue by ZyloV** [jcdesimp/Landlord#29]

**Comment by ZyloV** [comment]
Sorry for not entering a description, accidently hit enter. Well, I have a survival world and have this plugin, great plugin too. But players have been able to blow them up with creepers and tnt. I don't know who to ban because they lure the creepers so I was wondering if there is a way to protect people from tnt/creeper explosions by default on their land.

**Comment by jcdesimp** [comment]
Tnt explosions should be blocked, by the TNT flag if you want to disable Creepers then you'll have to use another plugin for now to disable them globally. I may add a creeper explosion flag in the future.

**Comment by ZyloV** [comment]
Please do, that would be super fantastic. Thank you!
