### ISSUE TITLE
Error when using /land claim

### ISSUE THREAD

**Issue by obiedog** [jcdesimp/Landlord#34]
This is very similar to #21 using world guard 6.1 and Landlord 1.3. The command still runs however I get the "An internal server error has occurred while attempting to perform this command" message even though the commands still run. However /land addfriend does not seem to go through. The error still occurs when the world guard integration is disabled.

**Comment by Battelman2** [comment]
Versions fully supporting Minecraft 1.9, also addressing bugs persisting from 1.8 to 1.9, are officially in development. Thank you for your patience thus far, whether or not you still use this plugin, three months is a long time.

**Comment by Battelman2** [comment]
Investigating for version 1.4. It's likely an issue with the noise made during land claiming, which is why the claim still works but throws the error. This will be fixed for 1.4.

**Comment by TheFluffyWalrus** [comment]
I have this resolved

**Comment by Battelman2** [comment]
This has been resolved in the latest commit. Expect an official Minecraft 1.9 release in the near future.
