### ISSUE TITLE
Lost protections after renaming world.

### ISSUE THREAD

**Issue by fredrik-j-lindberg** [jcdesimp/Landlord#44]
Hello!

I have changed the name of our world containing the landlord protections, which obviously makes the plugin think that there are no protections in that world anymore since they are stored by world name.

I was wondering if there is a way to change the world name of the protections, and if not, if you could add that? One solution would be to add MySQL support for the protections, as it is very easy to change properties such as world names within MySQL. Another solution would be to add a "/landlord changeworldname <current name> <new name>"- command.

Hopefully I won't have to reset all my protections, that will make my players somewhat upset xD

Either way, thanks for updating!

**Comment by Battelman2** [comment]
Looking into it. Is it something you need ASAP? Otherwise I cannot guarantee this will be taken care of immediately.

**Comment by Neylion** [comment]
Yeah, I'd say I need it ASAP. We'll introduce the changes soon after next weekend.

If it isn't done by then we'll just have to either remove Landlord until it is fixed, or remove all protections and start over.

If you don't have time for it, I understand. But it would really be awesome if you could do it ^.^

**Comment by Battelman2** [comment]
I'll see what I can do.

**Comment by Battelman2** [comment]
I am writing a separate script to handle this type of migration, which should be ready within a week. A more permanent solution is also in the pipeline.

**Comment by Neylion** [comment]
Thank you! :)

**Comment by Battelman2** [comment]
@Neylion the timeframe was greatly delayed, but has not been abandoned. I suspect you may have given up on waiting, reasonably speaking, but this enhancement will be added nonetheless in the near future. My apologies for the inconvenience.
